"""UniMate's own joint labels as a lookup: every raw bone name in its published data (UniML3D cond.npy: Objaverse,
Truebones) that UniMate's annotation (rule + language model) labelled consistently (>= 90% of its occurrences), with
the Objaverse export's per-joint index suffixes ('_013', '_1_053') stripped.

Writes the shipped table (all rigs) as C# and a held-out table (without the skeletons NamingAgreementTests scores) as
a test fixture, so the test measures how the table generalises to rigs it has not seen.

Run: D:\\99-scratch\\unimate\\.venv\\Scripts\\python.exe make_name_table.py <repo root>
"""
import collections
import json
import os
import re
import sys

import numpy as np

ROOT = sys.argv[1]
DATA = r"D:\99-scratch\uniml3d"
sources = [np.load(os.path.join(DATA, f"features__{d}__cond.npy"), allow_pickle=True).item() for d in ("objaverse", "truebones")]
held = {s["key"] for s in json.load(open(os.path.join(ROOT, "dev/Tests/fixtures/upstream_names/dataset_skeletons.json")))}


def norm(raw):
    return re.sub(r"(_\d+)+$", "", raw)


def engine(name):  # the engine's model compiler turns symbols other than '_' into '_'
    return "".join(c if c.isalnum() or c == "_" else "_" for c in name)


def build(exclude):
    counts = collections.defaultdict(collections.Counter)
    for src in sources:
        for key, c in src.items():
            if key in exclude:
                continue
            for raw, clean in zip(c["joint_names"], c["clean_joint_names"]):
                raw = str(raw)
                for k in {norm(raw), norm(engine(raw))}:
                    counts[k][str(clean)] += 1
    table = {}
    for k, c in counts.items():
        label, n = c.most_common(1)[0]
        if n / sum(c.values()) >= 0.9:
            table[k] = label
    return table


full = build(set())
labels = sorted(set(full.values()))
index = {l: i for i, l in enumerate(labels)}
lines = "\n".join(f"{k}\t{index[v]}" for k, v in sorted(full.items()))
labels_cs = ", ".join(json.dumps(l) for l in labels)
cs = f'''// Generated by dev/tools/upstream_prep/make_name_table.py from UniMate's published UniML3D data - do not edit.
namespace TextToAnimation.Editor.Inference.UniMate;

static partial class UniMateNameTable
{{
	static readonly string[] Labels = {{ {labels_cs} }};

	/// <summary>raw name (index suffixes stripped) TAB label index, one per line.</summary>
	const string Entries = {json.dumps(lines)};
}}
'''
open(os.path.join(ROOT, "Editor/TextToAnimation/Inference/UniMate/UniMateNameTable.Data.cs"), "w", encoding="utf-8").write(cs)
json.dump(build(held), open(os.path.join(ROOT, "dev/Tests/fixtures/upstream_names/name_table_heldout.json"), "w"))
print(f"{len(full)} names, {len(labels)} labels")
