using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace TextToAnimation.Editor.Inference.UniMate;

/// <summary>
/// UniMate's own labels for raw bone names it has seen: every raw name in its published data (UniML3D: 6149 Objaverse
/// rigs, 74 Truebones animals) that its annotation - rule and language model - labelled consistently. A rig whose
/// bones carry such names (Bip01_*, mixamorig:*, Blender .L/.R conventions and the like) gets exactly the label
/// UniMate gave them; the rest go through the rule and <see cref="UniMateNaming"/>. Generated by
/// dev/tools/upstream_prep/make_name_table.py.
/// </summary>
public static partial class UniMateNameTable
{
	static Dictionary<string, string> _table;

	/// <summary>Replaces the table (tests score the naming on rigs the table was built without).</summary>
	public static void Use( Dictionary<string, string> table ) => _table = table;

	static Dictionary<string, string> Table
	{
		get
		{
			if ( _table is not null ) return _table;
			var table = new Dictionary<string, string>( 40000, StringComparer.Ordinal );
			foreach ( var line in Entries.Split( '\n' ) )
			{
				var tab = line.IndexOf( '\t' );
				if ( tab > 0 ) table[line[..tab]] = Labels[int.Parse( line[(tab + 1)..] )];
			}
			return _table = table;
		}
	}

	static readonly Regex IndexSuffix = new( @"(_\d+)+$", RegexOptions.Compiled );

	/// <summary>The label UniMate gave this raw bone name, or null when it never saw it (or labelled it inconsistently).</summary>
	public static string Lookup( string raw )
	{
		var key = string.IsNullOrEmpty( raw ) ? "" : IndexSuffix.Replace( raw, "" );
		return key.Length > 0 && Table.TryGetValue( key, out var label ) ? label : null;
	}
}
